#!/bin/bash

echo "======================================"
echo "  📚 Hexo 博客项目结构"
echo "======================================"
echo ""

cd "$(dirname "$0")"

tree -L 2 -I 'node_modules|.git|public|.deploy_git' --charset ascii

echo ""
echo "======================================"
echo "  ℹ️  项目信息"
echo "======================================"
echo ""
echo "框架: Hexo $(npx hexo version | grep hexo: | cut -d' ' -f2)"
echo "主题: Butterfly 5.5.4"
echo "语言: 简体中文"
echo ""
echo "======================================"
echo "  📝 文章统计"
echo "======================================"
echo ""
echo "文章数量: $(ls -1 source/_posts/*.md 2>/dev/null | wc -l | xargs)"
echo ""
echo "======================================"
echo "  🔗 快速链接"
echo "======================================"
echo ""
echo "本地访问: http://localhost:4000"
echo "配置文件: _config.yml"
echo "主题配置: _config.butterfly.yml"
echo "文章目录: source/_posts/"
echo ""
echo "======================================"
echo "  📖 常用命令"
echo "======================================"
echo ""
echo "启动服务: ./start.sh"
echo "创建文章: npx hexo new \"标题\""
echo "清理缓存: npx hexo clean"
echo "生成网站: npx hexo generate"
echo ""
